# Generated by Django 4.2.1 on 2023-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(default='usuarios/icono-perfil.png', upload_to='usuarios'),
        ),
    ]
