# Generated by Django 4.2.1 on 2023-06-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_foto_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_comprado',
            fields=[
                ('cod_prod_c', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod_c', models.CharField(max_length=100)),
                ('precio_c', models.IntegerField()),
                ('foto_prod_c', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_comprado',
            fields=[
                ('id_detalle_c', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_c', models.IntegerField()),
                ('subtotal_c', models.IntegerField()),
                ('producto_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto_comprado')),
                ('venta_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
